### ISSUE TITLE
2/14 Sim UI: Forio -> Gravatar is blocked

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#620]
**1. Access to Gravatar shows resource is blocked:** 

I was unable to add a .jpg .png or .gif of the issue from my VA machine.
There is an issue with posting screenshots on GitHub, that apparently began yesterday.

Instead, I've copied my Inspector > Console text below:

> jquery-3.2.1.js:9455 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery-3.2.1.js:9455
2gravatar.com/avatar/f7f3a78d2a2cf1645688acdb7f460138?&d=404:1 

>Failed to load resource: the server responded with a status of 503 (Service Unavailable)
spplay.html:1 

> Access to XMLHttpRequest at 'https://gravatar.com/avatar/f7f3a78d2a2cf1645688acdb7f460138?&d=404' from origin 'https://forio.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_ 35 DEV/ 2 PM phrs. 

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@lzim Acknowledged.  I will investigate ways for the Sim UI to re-interrogate the gravitar server, so that the image is eventually displayed.  The error indicates a problem with their end, which does happen from time-to-time.

**Comment by lzim** [comment]
> @lzim Acknowledged. I will investigate ways for the Sim UI to re-interrogate the gravitar server, so that the image is eventually displayed. The error indicates a problem with their end, which does happen from time-to-time.

Thanks @jamesmrollins!

Yes, this has happened intermittently since the beginning. But, it is becoming more frequent, which is why I opened the issue: 1) we do want to created updated .gifs and .jpgs with “presence” (i.e., with team member’s images), and 2) we also are getting ready to launch with frontline staff who will never meet some of us face-to-face.

**Comment by jamesmrollins** [comment]
@lzim @staceypark @jessfroe @ritahitching we implemented a bit of code that will re-attempt, although not indefinitely, to re-establish connection with the Gravatar server, if one isn't established during the initial loading of the web page. Please advise me right away, with appropriate console screen capture, if the Gravatar fails to load in the future.  Thanks, James

**Comment by lzim** [comment]
@lzim @staceypark @jessfroe @ritahitching we implemented a bit of code that will re-attempt, although not indefinitely, to re-establish connection with the Gravatar server, if one isn't established during the initial loading of the web page. Please advise me right away, with appropriate console screen capture, if the Gravatar fails to load in the future. Thanks, James

- Will do @jamesmrollins

 HQ: we have to get to the bottom of why we cannot take screen captures in the VA right now too

**Comment by staceypark** [comment]
@jamesmrollins still failing to load. Sent you screenshot via email

**Comment by jamesmrollins** [comment]
@staceypark how long were you in the session?  Based on the error code, the resource is not available at their end, or the domain is blocking it.  I will run it past @hirenp-waferwire anyway, but suspect that is the issue.  Our code should keep rechecking until it loads a Gravatar.  That's why I need to know how long you had the window open.

@hirenp-waferwire see error from console below:

![image](https://user-images.githubusercontent.com/30132017/65651417-2d1cf500-dfc3-11e9-9577-4d1195956125.png)

**Comment by staceypark** [comment]
@jamesmrollins at least 20min+

**Comment by jamesmrollins** [comment]
@staceypark I discussed this with DEV.  Bottom line is that it is a domain blocking issue.  The fact that it checked even after 20 minutes means our code is working.  I'm not sure I can do any more with this issue.

**Comment by lzim** [comment]
> @staceypark I discussed this with DEV. Bottom line is that it is a domain blocking issue. The fact that it checked even after 20 minutes means our code is working. I'm not sure I can do any more with this issue.

@jamesmrollins and Forio has no other ways to get images in the Sim? Say at least for a known set of facilitators, even if not for all learners?

**Comment by staceypark** [comment]
@jamesmrollins is going to pursue a National helpdesk ticket first. Based on their response, we will re-evaluate by 10/15 on next steps.

**Comment by jamesmrollins** [comment]
@lzim FYSA

@jamesmrollins will investigate picture management alternatives that will:
1.  Provide a method for user-level upload of pictures.
2.  Maintain pictures from within Epicenter.
3. Perhaps show facilitator picture to teams, and team pictures to facilitator.

**Comment by staceypark** [comment]
@jamesmrollins is holding off on the National helpdesk ticket for now.

**Comment by jamesmrollins** [comment]
@lzim @staceypark  it is possible for us to manage photos in Epicenter by using the data API.  We can also create an upload utility that so the user can choose and upload a photo, format it to the frame and save to the API.  We will likely have to put this function on the button bar on the top of the screen.  Between DEV and Design it will take about 20 hours with testing and configuration.

**Comment by staceypark** [comment]
@jamesmrollins has also proposed that we can use this with the team website from the facilitator dashboard end.

**Comment by lzim** [comment]
Thanks for your work on this @jamesmrollins !

>  it is possible for us to manage photos in Epicenter by using the data API. We can also create an upload utility that so the user can choose and upload a photo, format it to the frame and save to the API. We will likely have to put this function on the button bar on the top of the screen. Between DEV and Design it will take about 20 hours with testing and configuration.
- Approved.
> use this with the team website from the facilitator dashboard end.
- Great!

FYI: @staceypark

**Comment by jamesmrollins** [comment]
These design instructions were delivered via email to DEV on 10/22, since GITHUB was not accepting graphics.  

**Estimate:** 20 Hrs for Items 1 and 2.  Item 3 estimate pending
**Design Objectives:**
1.  Install a button or link in the header of the Sim UI page header that will enable users to upload a picture.
2.  Install a utility that guides users through uploading a photo, centering the photo in a frame and then putting photo in the Sim Ui page header.
3.  Install same upload utility in the Team PSD website admin page. (let me know if this was not a part of original estimate – I don’t recall if we discussed this or not).

![image](https://user-images.githubusercontent.com/30132017/67448599-559d0c80-f5cc-11e9-81ca-da118b06ba0f.png)

![image](https://user-images.githubusercontent.com/30132017/67448695-9f85f280-f5cc-11e9-9431-e5ce22bdde25.png)

![image](https://user-images.githubusercontent.com/30132017/67448703-a9a7f100-f5cc-11e9-9c81-309714f02ac9.png)

**Comment by lzim** [comment]
Thanks @jamesmrollins 

- looking at this with the other cost estimates/work break downs against the overall budget.
- TBD ASAP.

FYI: @staceypark

**Comment by jamesmrollins** [comment]
Hi @lzim , @staceypark @ritahitching 
The estimate for item 3 is an additional 15 hours, for a total of 35 hrs DEV for this project.  I will likely spend up to 2 hrs testing and administering the change.  I have updated the estimate above.

**Comment by lzim** [comment]
Thanks @jamesmrollins 

- So, a total of 35 hours to include step 3.
- 1 and 2 are definitely an important functionality for maintaining “presence” in a participatory project.

I am weighing the cost of 3 above with the cost and project breakdown in the pending Sim Tutorial #775 & participatory button #334, which also seem key for learners in the field.

- We do have several team members joining us, so, if we add 5 team members is that worth 15 DEV + TESTING hours? 

Thoughts? @staceypark @jamesmrollins 
Maybe so, I welcome your recommendation based on how much the status quo for 3 costs. Thanks!

**Comment by jamesmrollins** [comment]
@lzim good question, and definitely a judgment call. If your goal is to preserve hours between now and April, so we can apply more towards the tutorial and the Go Live, I think we could safely put it in the future tracker.

**Comment by lzim** [comment]
Thanks @jamesmrollins 

This is really helpful.
- I’d like to proceed with 1 and 2 for 20 hours.
- And, I’d like to separate 3 and save for a future release.

**Comment by jamesmrollins** [comment]
@lzim - WILCO

@hirenp-waferwire we are not going to install the photo upload to the Team PSD admin page at this time.  We will likely include in a future release.

Thank you,
James

**Comment by jamesmrollins** [comment]
Item 3 above has been split from this issue into #782

**Comment by ritahitching** [comment]
Should be ready to test later this week - @jamesmrollins will ask team members to upload their photos to test the process within the VA

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire .  This function is looking good.  See below for some feedback.

**This function is working well.**
![image](https://user-images.githubusercontent.com/30132017/68360934-bf420e00-00d6-11ea-9266-b17649560d90.png)

**Regarding the ability to manipulate the photo.**
![image](https://user-images.githubusercontent.com/30132017/68360917-ad606b00-00d6-11ea-95bb-a6441cc72ca9.png)

**Comment by jamesmrollins** [comment]
@hirenp-waferwire please make the following changes:

![image](https://user-images.githubusercontent.com/30132017/68407007-a7e73d00-0137-11ea-8c7f-67fd4bdd601b.png)

**Comment by jamesmrollins** [comment]
Hi @lzim @staceypark @ritahitching @saveth @TomRust @branscombj @dlkibbe @dlounsbu take a look at this new photo upload feature!  It works pretty slick.  Just click the link shown highlighted below when you login to MTL, and upload your photo! Please let me know if you have any questions or concerns.  Thank you, James

![image](https://user-images.githubusercontent.com/30132017/68490253-8486c580-01fd-11ea-90ee-3870ebabb13d.png)

**Comment by staceypark** [comment]
@ritahitching can you test this out today?

**Comment by staceypark** [comment]
@jamesmrollins works great! 😄

**Comment by lzim** [comment]
@staceypark @ritahitching and @jamesmrollins 

- [ ] Can we get a brief training document on this and...
- [ ] send it to the OMHSP QIICs?

Thanks!

**Comment by ritahitching** [comment]
@jamesmrollins tested it too, looks good

**Comment by staceypark** [comment]
Works great in Test, will leave open until it is moved and tested in PROD as well

**Comment by staceypark** [comment]
@jamesmrollins I noticed you cross-referenced this in #949 as a sub-item to be completed together by 2/14. I updated the due date to match.

**Comment by staceypark** [comment]
this works in PROD, is already documented in the sim_cheatsheet, will be cross-refed in the meta_document card for facilitator training and can be closed.
